package errorHandling;

public enum ErrorType {
    UNDECLARED_IDENTIFIER,
    DUPLICATE_DECLARATION,
    TYPE_MISMATCH,
    CONST_REASSIGNMENT,
    NON_FUNCTION_CALL,
    INVALID_PROPERTY_ACCESS,
    UNREACHABLE_CODE,
    NULLABLE_PIPE_USE
}
